name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: | 
          az acr login --name danijus
          cd $GITHUB_WORKSPACE
          ls -al
          cat ./dockerfile | sed 's/http:\/\/localhost/https:\/\/danijus.com/g' > ./dockerfile.temp
          cp ./dockerfile.temp ./dockerfile
          echo "Here's the new dockerfile:"
          cat dockerfile
          docker build . -t danijus.azurecr.io/danijus:$GITHUB_RUN_ID
          docker push danijus.azurecr.io/danijus:$GITHUB_RUN_ID
          
          az webapp config container set --name danijus --resource-group danijus --docker-custom-image-name danijus.azurecr.io/danijus:$GITHUB_RUN_ID

