name: CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: acrLogin
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: | 
          login_output=$(az acr login --name danijus --expose-token)
          login_server=$(echo $login_output| jq '.loginServer')
          login_token=$(echo $login_output | jq '.accessToken')
          echo "::set-env name=docker_login_server::$login_server"
          echo "::set-env name=docker_login_tokenr::$login_token"
          
          
    - name: buildingImage
      run: | 
        docker login ${login_server} -u 00000000-0000-0000-0000-000000000000 -p ${login_token}
        
        cd $GITHUB_WORKSPACE
        ls -al
        cat ./dockerfile | sed 's/http:\/\/localhost/https:\/\/danijus.com/g' > ./dockerfile.temp
        cp ./dockerfile.temp ./dockerfile
        echo "Here's the new dockerfile:"
        cat dockerfile
        docker build . -t danijus.azurecr.io/danijus:$GITHUB_RUN_ID
        docker push danijus.azurecr.io/danijus:$GITHUB_RUN_ID

        
        
    - name: changingRunningEnv
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: | 
          az webapp config container set --name danijus --resource-group danijus --docker-custom-image-name danijus.azurecr.io/danijus:$GITHUB_RUN_ID
          
